### ISSUE TITLE
Error launching application on iPhone X.

### ISSUE THREAD

**Issue by kingfeng** [furuiCQ/flutter_echart#1]
Xcode's output:
flutter_echart-master/example/ios/Runner/GeneratedPluginRegistrant.m:11:4: error: use of undeclared identifier 'FlutterEchartPlugin'
[FlutterEchartPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterEchartPlugin"]];
       ^
    1 error generated.

**Comment by CoderHln** [comment]
一样的报错，但是我是在iPhone 6s上，找不到原因

**Comment by Fenice-steve** [comment]
/Users/sunpanyue/hurunflutter/flutter_echart-master/example/ios/Runner/GeneratedPluginRegistrant.m:11:4: error: use of undeclared identifier 'FlutterEchartPlugin'
      [FlutterEchartPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterEchartPlugin"]];

**Comment by Fenice-steve** [comment]
还有什么别的Echart插件吗

**Comment by furuiCQ** [comment]
原因是因为ios版，代码中并没有完善。

**Comment by furuiCQ** [comment]
new version is solve the problem
