### ISSUE TITLE
echarts重新渲染问题

### ISSUE THREAD

**Issue by HMYWorkSpace** [furuiCQ/flutter_echart#2]
兄弟，我在根据查询条件渲染是图表不更新。

**Comment by CoderHln** [comment]
图表不更新 应该是你没重新调用通道方法吧。这个用原生的view是没办法 setstate刷新的

**Comment by wssGod** [comment]
我用setstate方法还是没有刷新

**Comment by wssGod** [comment]
setState(() {
          option = {
            "tooltip": {
                "trigger": 'axis',
                "axisPointer": {
                    "animation": true
                }
            },

            "xAxis": {
                "type": 'time',
                "splitLine": {
                    "show": false
                }
            },
            "yAxis": {
                "type": 'value',
                "boundaryGap": [0, '100%'],
                "splitLine": {
                    "show": false
                }
            },
            "grid": {
                "top": 10,
                "left": 65,
                "bottom": 20,
            },
            "series": [{
                "name": '模拟数据',
                "type": 'line',
                "showSymbol": false,
                "hoverAnimation": false,
                "connectNulls": false,
                "data": currentPropertyData
            },
            ]
          };
        });

**Comment by furuiCQ** [comment]
new version fix this issues.
