### ISSUE TITLE
error: use of undeclared identifier 'FlutterEchartPlugin'

### ISSUE THREAD

**Issue by CoderHln** [furuiCQ/flutter_echart#3]
Xcode's output:
↳
    /Users/***/Downloads/flutter_echart-master 2/example/ios/Runner/GeneratedPluginRegistrant.m:11:4: error: use of undeclared identifier 'FlutterEchartPlugin'
      [FlutterEchartPlugin registerWithRegistrar:[registry registrarForPlugin:@"FlutterEchartPlugin"]];
       ^
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by android15125018** [comment]
作者将FlutterEchartPlugin这个文件的类名写成了FlutterNativeWebPlugin，要改一下，可以自己fork一份代码自己修改后在pubspec.yaml文件修改成依赖自己修改后的库即可，另外补充一点，iOS中webview的方法通道没写对也要改一下。

**Comment by furuiCQ** [comment]
new version has fix this issue 。thanks everyone
